Models/Categoria.cs
using System.Collections.Generic;

namespace APPBUSCO.Models
{
    public class Categoria
    {
         public int Id { get; set; }
        public string Nombre { get; set; }
        
        public ICollection<Producto> Productos {get; set;}

       
    }
}

Models/ErrorViewModel.cs
using System;

namespace APPBUSCO.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Producto.cs
namespace APPBUSCO.Models
{
    public class Producto
    {
       public int Id { get; set; }
        public string Nombre_del_Producto { get; set; }

        public string Url_Producto { get; set; }

        public string Descripcion { get; set; }

        public int Precio { get; set; }     

        public int Celular { get; set; }

        public string Lugar_De_Compra { get; set; }

        public string Nombre { get; set; } 

        
        public  Categoria Categoria { get; set; }

        public int CategoriaId {get; set;}
    }
}

Models/ProductoContext.cs
using Microsoft.EntityFrameworkCore;
namespace APPBUSCO.Models
{
    public class ProductoContext:DbContext
    {
        public  DbSet<Producto> Productos {get; set;}
        public  DbSet<Categoria> Categorias {get; set;}
        public ProductoContext(DbContextOptions dco) : base(dco) {
            
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using APPBUSCO.Models;

namespace APPBUSCO.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SolicitudesController.cs
using Microsoft.AspNetCore.Mvc;
using APPBUSCO.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace APPBUSCO.Controllers
{
    public class SolicitudesController:Controller
    {
        private readonly ProductoContext _context;
        public SolicitudesController(ProductoContext context){
            _context = context;

        }

        private IActionResult Productos()
        {
            var productos = _context.Productos.Include(x => x.Categoria).OrderBy(r => r.Nombre).ToList();
            return View(productos);
        }

        public IActionResult NuevoProducto(){
            ViewBag.categorias= _context.Categorias.ToList().Select(r => new SelectListItem(r.Nombre, r.Id.ToString()));
            return View();
        }
        [HttpPost]
        public IActionResult NuevoProducto(Producto r){
            if(ModelState.IsValid)
            {
                _context.Add(r);
                _context.SaveChanges();
                return RedirectToAction("NuevoProductoConfirmacion");
            }
            return View(r);
        }
        public IActionResult NuevoProductoConfirmacion(){
            return View();
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APPBUSCO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APPBUSCO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitudes" asp-action="Productos">Lista Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - APPBUSCO - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Solicitudes/Categorias.cshtml
@model List<Producto>

<h1>Lista de Productos</h1>

<table class="table border">
    <tr>
        <th>Id</th>
        <th>Nombre de producto</th>
        <th>url</th>
        <th>Descripcion</th>
        <th>Precio</th>
        <th>Celular</th>
        <th>Lugar de compran</th>
        <th>Nombre del Comprador</th>
    </tr>
    <!--Item para cada Producto-->
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Nombre_del_Producto</td>
            <td>@item.Url_Producto </td>
            <td>@item.Descripcion </td>
            <td>@item.Precio </td>
            <td>@item.Celular  </td>
            <td>@item.Lugar_De_Compra</td>
            <td>@item.Nombre</td>

            <td>
               <a href="/solicitudes/editarproducto/@item.Id" class="btn btn-secondary">Editar</a>
    
            <form action="/solicitudes/borrarproducto" method="POST" class="d-inline-block">
            <button class="btn btn-danger">Borrar</button>
            <input type="hidden" name="id" value="@item.Id" />
            </form>
            </td>
            
        </tr>
    }

     @if (Model.Count == 0) {
        <tr>
            <td colspan="4" class="text-center">No se encontraron productos</td>
        </tr>
        }
    
</table>
<a href="/ubicaciones/nuevaregion/" class="btn btn-primary">Añadir Region</a>

Views/Solicitudes/NuevaCategoria.cshtml
@model Producto

<h1>Nuevo Producto</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Categoria"></label>
        <select asp-for="CategoriaId" asp-items="ViewBag.categorias" type="text" class="form-control"></select>
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Solicitudes/NuevoProducto.cshtml
@model Producto

<h1>Nuevo Producto</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Categoria"></label>
        <select asp-for="CategoriaId" asp-items="ViewBag.categorias" type="text" class="form-control"></select>
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Solicitudes/NuevoProductoConfirmacion.cshtml
<h1>NuevoProducto</h1>
<p>ElProducto fue creado con exito</p>

Views/Solicitudes/Producto.cshtml
@model List<Producto>

<h1>Lista de Productos</h1>

<table class="table border">
    <tr>
        <th>Id</th>
        <th>Nombre de producto</th>
        <th>url</th>
        <th>Descripcion</th>
        <th>Precio</th>
        <th>Celular</th>
        <th>Lugar de compran</th>
        <th>Nombre del Comprador</th>
    </tr>
    <!--Item para cada Producto-->
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Nombre_del_Producto</td>
            <td>@item.Url_Producto </td>
            <td>@item.Descripcion </td>
            <td>@item.Precio </td>
            <td>@item.Celular  </td>
            <td>@item.Lugar_De_Compra</td>
            <td>@item.Nombre</td>

            <td>
               <a href="/solicitudes/editarproducto/@item.Id" class="btn btn-secondary">Editar</a>
    
            <form action="/solicitudes/borrarproducto" method="POST" class="d-inline-block">
            <button class="btn btn-danger">Borrar</button>
            <input type="hidden" name="id" value="@item.Id" />
            </form>
            </td>
            
        </tr>
    }

     @if (Model.Count == 0) {
        <tr>
            <td colspan="4" class="text-center">No se encontraron productos</td>
        </tr>
        }
    
</table>
<a href="/ubicaciones/nuevaregion/" class="btn btn-primary">Añadir Region</a>